apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard
  name: kuard
spec:
        #  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard
  sessionAffinity: None
